package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.AppBizType;
import com.treefinance.saas.grapserver.dao.entity.AppBizTypeCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AppBizTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    long countByExample(AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int deleteByExample(AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int insert(AppBizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int insertSelective(AppBizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    List<AppBizType> selectByExampleWithRowbounds(AppBizTypeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    List<AppBizType> selectByExample(AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    List<AppBizType> selectPaginationByExample(AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int insertOrUpdateBySelective(AppBizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    void batchInsert(List<AppBizType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AppBizType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AppBizType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    AppBizType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppBizType record, @Param("example") AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int updateByExample(@Param("record") AppBizType record, @Param("example") AppBizTypeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int updateByPrimaryKeySelective(AppBizType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_type
     *
     * @mbg.generated Thu Aug 03 17:10:59 CST 2017
     */
    int updateByPrimaryKey(AppBizType record);
}