package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.AppCallbackBiz;
import com.treefinance.saas.grapserver.dao.entity.AppCallbackBizCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AppCallbackBizMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    long countByExample(AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int deleteByExample(AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int insert(AppCallbackBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int insertSelective(AppCallbackBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    List<AppCallbackBiz> selectByExampleWithRowbounds(AppCallbackBizCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    List<AppCallbackBiz> selectByExample(AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    List<AppCallbackBiz> selectPaginationByExample(AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int insertOrUpdateBySelective(AppCallbackBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    void batchInsert(List<AppCallbackBiz> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AppCallbackBiz> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AppCallbackBiz> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    AppCallbackBiz selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppCallbackBiz record, @Param("example") AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int updateByExample(@Param("record") AppCallbackBiz record, @Param("example") AppCallbackBizCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int updateByPrimaryKeySelective(AppCallbackBiz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_biz
     *
     * @mbg.generated Mon Jul 24 17:49:00 CST 2017
     */
    int updateByPrimaryKey(AppCallbackBiz record);
}