package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.AppCallbackConfig;
import com.treefinance.saas.grapserver.dao.entity.AppCallbackConfigCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface AppCallbackConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    long countByExample(AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int deleteByExample(AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int insert(AppCallbackConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int insertSelective(AppCallbackConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    List<AppCallbackConfig> selectByExampleWithRowbounds(AppCallbackConfigCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    List<AppCallbackConfig> selectByExample(AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    List<AppCallbackConfig> selectPaginationByExample(AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int insertOrUpdateBySelective(AppCallbackConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    void batchInsert(List<AppCallbackConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    void batchUpdateByPrimaryKey(List<AppCallbackConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    void batchUpdateByPrimaryKeySelective(List<AppCallbackConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    AppCallbackConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int updateByExampleSelective(@Param("record") AppCallbackConfig record, @Param("example") AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int updateByExample(@Param("record") AppCallbackConfig record, @Param("example") AppCallbackConfigCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int updateByPrimaryKeySelective(AppCallbackConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_callback_config
     *
     * @mbg.generated Wed Jul 26 14:09:48 CST 2017
     */
    int updateByPrimaryKey(AppCallbackConfig record);
}