package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.MerchantBaseInfo;
import com.treefinance.saas.grapserver.dao.entity.MerchantBaseInfoCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface MerchantBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int countByExample(MerchantBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int deleteByExample(MerchantBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int insert(MerchantBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int insertSelective(MerchantBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    List<MerchantBaseInfo> selectByExampleWithRowbounds(MerchantBaseInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    List<MerchantBaseInfo> selectByExample(MerchantBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    MerchantBaseInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int updateByExampleSelective(@Param("record") MerchantBaseInfo record, @Param("example") MerchantBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int updateByExample(@Param("record") MerchantBaseInfo record, @Param("example") MerchantBaseInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int updateByPrimaryKeySelective(MerchantBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Wed Jun 14 21:56:13 CST 2017
     */
    int updateByPrimaryKey(MerchantBaseInfo record);
}