package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskOperatorMaintainUserLog;
import com.treefinance.saas.grapserver.dao.entity.TaskOperatorMaintainUserLogCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TaskOperatorMaintainUserLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int countByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int deleteByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int insert(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int insertSelective(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    List<TaskOperatorMaintainUserLog> selectByExampleWithRowbounds(TaskOperatorMaintainUserLogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    List<TaskOperatorMaintainUserLog> selectByExample(TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    TaskOperatorMaintainUserLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskOperatorMaintainUserLog record, @Param("example") TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int updateByExample(@Param("record") TaskOperatorMaintainUserLog record, @Param("example") TaskOperatorMaintainUserLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int updateByPrimaryKeySelective(TaskOperatorMaintainUserLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_operator_maintain_user_log
     *
     * @mbggenerated Fri Oct 27 14:05:08 CST 2017
     */
    int updateByPrimaryKey(TaskOperatorMaintainUserLog record);
}