package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskSupport;
import com.treefinance.saas.grapserver.dao.entity.TaskSupportCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TaskSupportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int countByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int deleteByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int insert(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int insertSelective(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    List<TaskSupport> selectByExampleWithRowbounds(TaskSupportCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    List<TaskSupport> selectByExample(TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    TaskSupport selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskSupport record, @Param("example") TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int updateByExample(@Param("record") TaskSupport record, @Param("example") TaskSupportCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int updateByPrimaryKeySelective(TaskSupport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    int updateByPrimaryKey(TaskSupport record);
}