package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskLog;
import com.treefinance.saas.grapserver.dao.entity.TaskLogCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TaskLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int countByExample(TaskLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int deleteByExample(TaskLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int insert(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int insertSelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    List<TaskLog> selectByExampleWithRowbounds(TaskLogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    List<TaskLog> selectByExample(TaskLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    TaskLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskLog record, @Param("example") TaskLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int updateByExample(@Param("record") TaskLog record, @Param("example") TaskLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int updateByPrimaryKeySelective(TaskLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbggenerated Wed Aug 23 14:51:20 CST 2017
     */
    int updateByPrimaryKey(TaskLog record);
}