package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskDevice;
import com.treefinance.saas.grapserver.dao.entity.TaskDeviceCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TaskDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int countByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int deleteByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int insert(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int insertSelective(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    List<TaskDevice> selectByExampleWithRowbounds(TaskDeviceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    List<TaskDevice> selectByExample(TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    TaskDevice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskDevice record, @Param("example") TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int updateByExample(@Param("record") TaskDevice record, @Param("example") TaskDeviceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int updateByPrimaryKeySelective(TaskDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_device
     *
     * @mbggenerated Wed May 03 19:48:10 CST 2017
     */
    int updateByPrimaryKey(TaskDevice record);
}