package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskAttribute;
import com.treefinance.saas.grapserver.dao.entity.TaskAttributeCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TaskAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int countByExample(TaskAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int deleteByExample(TaskAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int insert(TaskAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int insertSelective(TaskAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    List<TaskAttribute> selectByExampleWithRowbounds(TaskAttributeCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    List<TaskAttribute> selectByExample(TaskAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    TaskAttribute selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskAttribute record, @Param("example") TaskAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int updateByExample(@Param("record") TaskAttribute record, @Param("example") TaskAttributeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int updateByPrimaryKeySelective(TaskAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_attribute
     *
     * @mbggenerated Wed Jul 05 15:00:03 CST 2017
     */
    int updateByPrimaryKey(TaskAttribute record);
}