package com.treefinance.saas.grapserver.dao.mapper;

import com.treefinance.saas.grapserver.dao.entity.TaskCallbackLog;
import com.treefinance.saas.grapserver.dao.entity.TaskCallbackLogCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TaskCallbackLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int countByExample(TaskCallbackLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int deleteByExample(TaskCallbackLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int insert(TaskCallbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int insertSelective(TaskCallbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    List<TaskCallbackLog> selectByExampleWithRowbounds(TaskCallbackLogCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    List<TaskCallbackLog> selectByExample(TaskCallbackLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    TaskCallbackLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskCallbackLog record, @Param("example") TaskCallbackLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int updateByExample(@Param("record") TaskCallbackLog record, @Param("example") TaskCallbackLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int updateByPrimaryKeySelective(TaskCallbackLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_callback_log
     *
     * @mbggenerated Fri Aug 18 11:53:16 CST 2017
     */
    int updateByPrimaryKey(TaskCallbackLog record);
}