/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.grapserver.biz.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class AppBizLicense implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.Id
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.AppId
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.BizType
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte bizType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.isShowLicense
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte isShowLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.LicenseTemplate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private String licenseTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.isValid
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.DailyLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Integer dailyLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.TrafficLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private BigDecimal trafficLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.h5Access
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte h5Access;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.sdkAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte sdkAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.apiAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Byte apiAccess;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.questionaireRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Integer questionaireRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.feedbackRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Integer feedbackRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.CreateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_biz_license.LastUpdateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.Id
     *
     * @return the value of app_biz_license.Id
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.Id
     *
     * @param id the value for app_biz_license.Id
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.AppId
     *
     * @return the value of app_biz_license.AppId
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.AppId
     *
     * @param appId the value for app_biz_license.AppId
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.BizType
     *
     * @return the value of app_biz_license.BizType
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getBizType() {
        return bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.BizType
     *
     * @param bizType the value for app_biz_license.BizType
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.isShowLicense
     *
     * @return the value of app_biz_license.isShowLicense
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getIsShowLicense() {
        return isShowLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.isShowLicense
     *
     * @param isShowLicense the value for app_biz_license.isShowLicense
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setIsShowLicense(Byte isShowLicense) {
        this.isShowLicense = isShowLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.LicenseTemplate
     *
     * @return the value of app_biz_license.LicenseTemplate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public String getLicenseTemplate() {
        return licenseTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.LicenseTemplate
     *
     * @param licenseTemplate the value for app_biz_license.LicenseTemplate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setLicenseTemplate(String licenseTemplate) {
        this.licenseTemplate = licenseTemplate == null ? null : licenseTemplate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.isValid
     *
     * @return the value of app_biz_license.isValid
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.isValid
     *
     * @param isValid the value for app_biz_license.isValid
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setIsValid(Byte isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.DailyLimit
     *
     * @return the value of app_biz_license.DailyLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Integer getDailyLimit() {
        return dailyLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.DailyLimit
     *
     * @param dailyLimit the value for app_biz_license.DailyLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setDailyLimit(Integer dailyLimit) {
        this.dailyLimit = dailyLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.TrafficLimit
     *
     * @return the value of app_biz_license.TrafficLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public BigDecimal getTrafficLimit() {
        return trafficLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.TrafficLimit
     *
     * @param trafficLimit the value for app_biz_license.TrafficLimit
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setTrafficLimit(BigDecimal trafficLimit) {
        this.trafficLimit = trafficLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.h5Access
     *
     * @return the value of app_biz_license.h5Access
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getH5Access() {
        return h5Access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.h5Access
     *
     * @param h5Access the value for app_biz_license.h5Access
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setH5Access(Byte h5Access) {
        this.h5Access = h5Access;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.sdkAccess
     *
     * @return the value of app_biz_license.sdkAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getSdkAccess() {
        return sdkAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.sdkAccess
     *
     * @param sdkAccess the value for app_biz_license.sdkAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setSdkAccess(Byte sdkAccess) {
        this.sdkAccess = sdkAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.apiAccess
     *
     * @return the value of app_biz_license.apiAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Byte getApiAccess() {
        return apiAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.apiAccess
     *
     * @param apiAccess the value for app_biz_license.apiAccess
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setApiAccess(Byte apiAccess) {
        this.apiAccess = apiAccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.questionaireRate
     *
     * @return the value of app_biz_license.questionaireRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Integer getQuestionaireRate() {
        return questionaireRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.questionaireRate
     *
     * @param questionaireRate the value for app_biz_license.questionaireRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setQuestionaireRate(Integer questionaireRate) {
        this.questionaireRate = questionaireRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.feedbackRate
     *
     * @return the value of app_biz_license.feedbackRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Integer getFeedbackRate() {
        return feedbackRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.feedbackRate
     *
     * @param feedbackRate the value for app_biz_license.feedbackRate
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setFeedbackRate(Integer feedbackRate) {
        this.feedbackRate = feedbackRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.CreateTime
     *
     * @return the value of app_biz_license.CreateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.CreateTime
     *
     * @param createTime the value for app_biz_license.CreateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_biz_license.LastUpdateTime
     *
     * @return the value of app_biz_license.LastUpdateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_biz_license.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_biz_license.LastUpdateTime
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", bizType=").append(bizType);
        sb.append(", isShowLicense=").append(isShowLicense);
        sb.append(", licenseTemplate=").append(licenseTemplate);
        sb.append(", isValid=").append(isValid);
        sb.append(", dailyLimit=").append(dailyLimit);
        sb.append(", trafficLimit=").append(trafficLimit);
        sb.append(", h5Access=").append(h5Access);
        sb.append(", sdkAccess=").append(sdkAccess);
        sb.append(", apiAccess=").append(apiAccess);
        sb.append(", questionaireRate=").append(questionaireRate);
        sb.append(", feedbackRate=").append(feedbackRate);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}