/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.grapserver.biz.dto;

import java.io.Serializable;
import java.util.Date;

public class AppColorConfig implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Id
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.AppId
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Style
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Main
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String main;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Assist
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String assist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.AssistError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String assistError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.BackBtnAndFontColor
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String backBtnAndFontColor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Background
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String background;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.BtnDisabled
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String btnDisabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.ScheduleError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private String scheduleError;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.Status
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.CreateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column app_color_config.LastUpdateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_color_config
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Id
     *
     * @return the value of app_color_config.Id
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Id
     *
     * @param id the value for app_color_config.Id
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.AppId
     *
     * @return the value of app_color_config.AppId
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.AppId
     *
     * @param appId the value for app_color_config.AppId
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Style
     *
     * @return the value of app_color_config.Style
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Style
     *
     * @param style the value for app_color_config.Style
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Main
     *
     * @return the value of app_color_config.Main
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getMain() {
        return main;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Main
     *
     * @param main the value for app_color_config.Main
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setMain(String main) {
        this.main = main == null ? null : main.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Assist
     *
     * @return the value of app_color_config.Assist
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getAssist() {
        return assist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Assist
     *
     * @param assist the value for app_color_config.Assist
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setAssist(String assist) {
        this.assist = assist == null ? null : assist.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.AssistError
     *
     * @return the value of app_color_config.AssistError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getAssistError() {
        return assistError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.AssistError
     *
     * @param assistError the value for app_color_config.AssistError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setAssistError(String assistError) {
        this.assistError = assistError == null ? null : assistError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.BackBtnAndFontColor
     *
     * @return the value of app_color_config.BackBtnAndFontColor
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getBackBtnAndFontColor() {
        return backBtnAndFontColor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.BackBtnAndFontColor
     *
     * @param backBtnAndFontColor the value for app_color_config.BackBtnAndFontColor
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setBackBtnAndFontColor(String backBtnAndFontColor) {
        this.backBtnAndFontColor = backBtnAndFontColor == null ? null : backBtnAndFontColor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Background
     *
     * @return the value of app_color_config.Background
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getBackground() {
        return background;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Background
     *
     * @param background the value for app_color_config.Background
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setBackground(String background) {
        this.background = background == null ? null : background.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.BtnDisabled
     *
     * @return the value of app_color_config.BtnDisabled
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getBtnDisabled() {
        return btnDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.BtnDisabled
     *
     * @param btnDisabled the value for app_color_config.BtnDisabled
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setBtnDisabled(String btnDisabled) {
        this.btnDisabled = btnDisabled == null ? null : btnDisabled.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.ScheduleError
     *
     * @return the value of app_color_config.ScheduleError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public String getScheduleError() {
        return scheduleError;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.ScheduleError
     *
     * @param scheduleError the value for app_color_config.ScheduleError
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setScheduleError(String scheduleError) {
        this.scheduleError = scheduleError == null ? null : scheduleError.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.Status
     *
     * @return the value of app_color_config.Status
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.Status
     *
     * @param status the value for app_color_config.Status
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.CreateTime
     *
     * @return the value of app_color_config.CreateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.CreateTime
     *
     * @param createTime the value for app_color_config.CreateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column app_color_config.LastUpdateTime
     *
     * @return the value of app_color_config.LastUpdateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column app_color_config.LastUpdateTime
     *
     * @param lastUpdateTime the value for app_color_config.LastUpdateTime
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_color_config
     *
     * @mbggenerated Mon Dec 25 14:33:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", style=").append(style);
        sb.append(", main=").append(main);
        sb.append(", assist=").append(assist);
        sb.append(", assistError=").append(assistError);
        sb.append(", backBtnAndFontColor=").append(backBtnAndFontColor);
        sb.append(", background=").append(background);
        sb.append(", btnDisabled=").append(btnDisabled);
        sb.append(", scheduleError=").append(scheduleError);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}