/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.grapserver.biz.dto;

import java.io.Serializable;
import java.util.Date;

public class MerchantBaseInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.Id
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.AppId
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.AppName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.ChName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String chName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.Company
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.Bussiness
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String bussiness;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.Bussiness2
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String bussiness2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.Address
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.ContactPerson
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String contactPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.ContactValue
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private String contactValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.CreateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchant_base.LastUpdateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table merchant_base
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.Id
     *
     * @return the value of merchant_base.Id
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.Id
     *
     * @param id the value for merchant_base.Id
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.AppId
     *
     * @return the value of merchant_base.AppId
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.AppId
     *
     * @param appId the value for merchant_base.AppId
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.AppName
     *
     * @return the value of merchant_base.AppName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.AppName
     *
     * @param appName the value for merchant_base.AppName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.ChName
     *
     * @return the value of merchant_base.ChName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getChName() {
        return chName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.ChName
     *
     * @param chName the value for merchant_base.ChName
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setChName(String chName) {
        this.chName = chName == null ? null : chName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.Company
     *
     * @return the value of merchant_base.Company
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.Company
     *
     * @param company the value for merchant_base.Company
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.Bussiness
     *
     * @return the value of merchant_base.Bussiness
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getBussiness() {
        return bussiness;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.Bussiness
     *
     * @param bussiness the value for merchant_base.Bussiness
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setBussiness(String bussiness) {
        this.bussiness = bussiness == null ? null : bussiness.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.Bussiness2
     *
     * @return the value of merchant_base.Bussiness2
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getBussiness2() {
        return bussiness2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.Bussiness2
     *
     * @param bussiness2 the value for merchant_base.Bussiness2
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setBussiness2(String bussiness2) {
        this.bussiness2 = bussiness2 == null ? null : bussiness2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.Address
     *
     * @return the value of merchant_base.Address
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.Address
     *
     * @param address the value for merchant_base.Address
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.ContactPerson
     *
     * @return the value of merchant_base.ContactPerson
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getContactPerson() {
        return contactPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.ContactPerson
     *
     * @param contactPerson the value for merchant_base.ContactPerson
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setContactPerson(String contactPerson) {
        this.contactPerson = contactPerson == null ? null : contactPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.ContactValue
     *
     * @return the value of merchant_base.ContactValue
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public String getContactValue() {
        return contactValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.ContactValue
     *
     * @param contactValue the value for merchant_base.ContactValue
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setContactValue(String contactValue) {
        this.contactValue = contactValue == null ? null : contactValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.CreateTime
     *
     * @return the value of merchant_base.CreateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.CreateTime
     *
     * @param createTime the value for merchant_base.CreateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchant_base.LastUpdateTime
     *
     * @return the value of merchant_base.LastUpdateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchant_base.LastUpdateTime
     *
     * @param lastUpdateTime the value for merchant_base.LastUpdateTime
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchant_base
     *
     * @mbggenerated Fri Oct 20 10:37:23 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appId=").append(appId);
        sb.append(", appName=").append(appName);
        sb.append(", chName=").append(chName);
        sb.append(", company=").append(company);
        sb.append(", bussiness=").append(bussiness);
        sb.append(", bussiness2=").append(bussiness2);
        sb.append(", address=").append(address);
        sb.append(", contactPerson=").append(contactPerson);
        sb.append(", contactValue=").append(contactValue);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}