/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.grapserver.biz.dto;

import java.io.Serializable;
import java.util.Date;

public class TaskBuryPointLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.id
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.taskId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.appId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.code
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.createTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_bury_point_log.lastUpdateTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.id
     *
     * @return the value of task_bury_point_log.id
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.id
     *
     * @param id the value for task_bury_point_log.id
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.taskId
     *
     * @return the value of task_bury_point_log.taskId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.taskId
     *
     * @param taskId the value for task_bury_point_log.taskId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.appId
     *
     * @return the value of task_bury_point_log.appId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.appId
     *
     * @param appId the value for task_bury_point_log.appId
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.code
     *
     * @return the value of task_bury_point_log.code
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.code
     *
     * @param code the value for task_bury_point_log.code
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.createTime
     *
     * @return the value of task_bury_point_log.createTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.createTime
     *
     * @param createTime the value for task_bury_point_log.createTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_bury_point_log.lastUpdateTime
     *
     * @return the value of task_bury_point_log.lastUpdateTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_bury_point_log.lastUpdateTime
     *
     * @param lastUpdateTime the value for task_bury_point_log.lastUpdateTime
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_bury_point_log
     *
     * @mbg.generated Thu Sep 21 20:46:15 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", appId=").append(appId);
        sb.append(", code=").append(code);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}