/*
 * Copyright © 2015 - 2017 杭州大树网络技术有限公司. All Rights Reserved
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.treefinance.saas.grapserver.biz.dto;

import java.io.Serializable;
import java.util.Date;

public class TaskNextDirective implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.Id
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.TaskId
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.Directive
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private String directive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.Remark
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.CreateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.LastUpdateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_next_directive
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.Id
     *
     * @return the value of task_next_directive.Id
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.Id
     *
     * @param id the value for task_next_directive.Id
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.TaskId
     *
     * @return the value of task_next_directive.TaskId
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.TaskId
     *
     * @param taskId the value for task_next_directive.TaskId
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.Directive
     *
     * @return the value of task_next_directive.Directive
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public String getDirective() {
        return directive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.Directive
     *
     * @param directive the value for task_next_directive.Directive
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setDirective(String directive) {
        this.directive = directive == null ? null : directive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.Remark
     *
     * @return the value of task_next_directive.Remark
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.Remark
     *
     * @param remark the value for task_next_directive.Remark
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.CreateTime
     *
     * @return the value of task_next_directive.CreateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.CreateTime
     *
     * @param createTime the value for task_next_directive.CreateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.LastUpdateTime
     *
     * @return the value of task_next_directive.LastUpdateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.LastUpdateTime
     *
     * @param lastUpdateTime the value for task_next_directive.LastUpdateTime
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_next_directive
     *
     * @mbg.generated Thu Jul 12 15:32:17 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", directive=").append(directive);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}