package com.treefinance.saas.grapserver.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppBizLicenseCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected int limit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected int offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public AppBizLicenseCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setLimit(int limit) {
        this.limit = limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public int getLimit() {
        return limit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setOffset(int offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public int getOffset() {
        return offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("AppId is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("AppId is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("AppId =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("AppId <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("AppId >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("AppId >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("AppId <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("AppId <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("AppId like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("AppId not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("AppId in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("AppId not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("AppId between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("AppId not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNull() {
            addCriterion("BizType is null");
            return (Criteria) this;
        }

        public Criteria andBizTypeIsNotNull() {
            addCriterion("BizType is not null");
            return (Criteria) this;
        }

        public Criteria andBizTypeEqualTo(Byte value) {
            addCriterion("BizType =", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotEqualTo(Byte value) {
            addCriterion("BizType <>", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThan(Byte value) {
            addCriterion("BizType >", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("BizType >=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThan(Byte value) {
            addCriterion("BizType <", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeLessThanOrEqualTo(Byte value) {
            addCriterion("BizType <=", value, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeIn(List<Byte> values) {
            addCriterion("BizType in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotIn(List<Byte> values) {
            addCriterion("BizType not in", values, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeBetween(Byte value1, Byte value2) {
            addCriterion("BizType between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andBizTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("BizType not between", value1, value2, "bizType");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseIsNull() {
            addCriterion("isShowLicense is null");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseIsNotNull() {
            addCriterion("isShowLicense is not null");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseEqualTo(Byte value) {
            addCriterion("isShowLicense =", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseNotEqualTo(Byte value) {
            addCriterion("isShowLicense <>", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseGreaterThan(Byte value) {
            addCriterion("isShowLicense >", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseGreaterThanOrEqualTo(Byte value) {
            addCriterion("isShowLicense >=", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseLessThan(Byte value) {
            addCriterion("isShowLicense <", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseLessThanOrEqualTo(Byte value) {
            addCriterion("isShowLicense <=", value, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseIn(List<Byte> values) {
            addCriterion("isShowLicense in", values, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseNotIn(List<Byte> values) {
            addCriterion("isShowLicense not in", values, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseBetween(Byte value1, Byte value2) {
            addCriterion("isShowLicense between", value1, value2, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andIsShowLicenseNotBetween(Byte value1, Byte value2) {
            addCriterion("isShowLicense not between", value1, value2, "isShowLicense");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateIsNull() {
            addCriterion("LicenseTemplate is null");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateIsNotNull() {
            addCriterion("LicenseTemplate is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateEqualTo(String value) {
            addCriterion("LicenseTemplate =", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateNotEqualTo(String value) {
            addCriterion("LicenseTemplate <>", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateGreaterThan(String value) {
            addCriterion("LicenseTemplate >", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateGreaterThanOrEqualTo(String value) {
            addCriterion("LicenseTemplate >=", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateLessThan(String value) {
            addCriterion("LicenseTemplate <", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateLessThanOrEqualTo(String value) {
            addCriterion("LicenseTemplate <=", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateLike(String value) {
            addCriterion("LicenseTemplate like", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateNotLike(String value) {
            addCriterion("LicenseTemplate not like", value, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateIn(List<String> values) {
            addCriterion("LicenseTemplate in", values, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateNotIn(List<String> values) {
            addCriterion("LicenseTemplate not in", values, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateBetween(String value1, String value2) {
            addCriterion("LicenseTemplate between", value1, value2, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andLicenseTemplateNotBetween(String value1, String value2) {
            addCriterion("LicenseTemplate not between", value1, value2, "licenseTemplate");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNull() {
            addCriterion("isValid is null");
            return (Criteria) this;
        }

        public Criteria andIsValidIsNotNull() {
            addCriterion("isValid is not null");
            return (Criteria) this;
        }

        public Criteria andIsValidEqualTo(Byte value) {
            addCriterion("isValid =", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotEqualTo(Byte value) {
            addCriterion("isValid <>", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThan(Byte value) {
            addCriterion("isValid >", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("isValid >=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThan(Byte value) {
            addCriterion("isValid <", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidLessThanOrEqualTo(Byte value) {
            addCriterion("isValid <=", value, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidIn(List<Byte> values) {
            addCriterion("isValid in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotIn(List<Byte> values) {
            addCriterion("isValid not in", values, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidBetween(Byte value1, Byte value2) {
            addCriterion("isValid between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andIsValidNotBetween(Byte value1, Byte value2) {
            addCriterion("isValid not between", value1, value2, "isValid");
            return (Criteria) this;
        }

        public Criteria andDailyLimitIsNull() {
            addCriterion("DailyLimit is null");
            return (Criteria) this;
        }

        public Criteria andDailyLimitIsNotNull() {
            addCriterion("DailyLimit is not null");
            return (Criteria) this;
        }

        public Criteria andDailyLimitEqualTo(Integer value) {
            addCriterion("DailyLimit =", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitNotEqualTo(Integer value) {
            addCriterion("DailyLimit <>", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitGreaterThan(Integer value) {
            addCriterion("DailyLimit >", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("DailyLimit >=", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitLessThan(Integer value) {
            addCriterion("DailyLimit <", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitLessThanOrEqualTo(Integer value) {
            addCriterion("DailyLimit <=", value, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitIn(List<Integer> values) {
            addCriterion("DailyLimit in", values, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitNotIn(List<Integer> values) {
            addCriterion("DailyLimit not in", values, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitBetween(Integer value1, Integer value2) {
            addCriterion("DailyLimit between", value1, value2, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andDailyLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("DailyLimit not between", value1, value2, "dailyLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitIsNull() {
            addCriterion("TrafficLimit is null");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitIsNotNull() {
            addCriterion("TrafficLimit is not null");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitEqualTo(BigDecimal value) {
            addCriterion("TrafficLimit =", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitNotEqualTo(BigDecimal value) {
            addCriterion("TrafficLimit <>", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitGreaterThan(BigDecimal value) {
            addCriterion("TrafficLimit >", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("TrafficLimit >=", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitLessThan(BigDecimal value) {
            addCriterion("TrafficLimit <", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("TrafficLimit <=", value, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitIn(List<BigDecimal> values) {
            addCriterion("TrafficLimit in", values, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitNotIn(List<BigDecimal> values) {
            addCriterion("TrafficLimit not in", values, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrafficLimit between", value1, value2, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andTrafficLimitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("TrafficLimit not between", value1, value2, "trafficLimit");
            return (Criteria) this;
        }

        public Criteria andH5AccessIsNull() {
            addCriterion("h5Access is null");
            return (Criteria) this;
        }

        public Criteria andH5AccessIsNotNull() {
            addCriterion("h5Access is not null");
            return (Criteria) this;
        }

        public Criteria andH5AccessEqualTo(Byte value) {
            addCriterion("h5Access =", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessNotEqualTo(Byte value) {
            addCriterion("h5Access <>", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessGreaterThan(Byte value) {
            addCriterion("h5Access >", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessGreaterThanOrEqualTo(Byte value) {
            addCriterion("h5Access >=", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessLessThan(Byte value) {
            addCriterion("h5Access <", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessLessThanOrEqualTo(Byte value) {
            addCriterion("h5Access <=", value, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessIn(List<Byte> values) {
            addCriterion("h5Access in", values, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessNotIn(List<Byte> values) {
            addCriterion("h5Access not in", values, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessBetween(Byte value1, Byte value2) {
            addCriterion("h5Access between", value1, value2, "h5Access");
            return (Criteria) this;
        }

        public Criteria andH5AccessNotBetween(Byte value1, Byte value2) {
            addCriterion("h5Access not between", value1, value2, "h5Access");
            return (Criteria) this;
        }

        public Criteria andSdkAccessIsNull() {
            addCriterion("sdkAccess is null");
            return (Criteria) this;
        }

        public Criteria andSdkAccessIsNotNull() {
            addCriterion("sdkAccess is not null");
            return (Criteria) this;
        }

        public Criteria andSdkAccessEqualTo(Byte value) {
            addCriterion("sdkAccess =", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessNotEqualTo(Byte value) {
            addCriterion("sdkAccess <>", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessGreaterThan(Byte value) {
            addCriterion("sdkAccess >", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessGreaterThanOrEqualTo(Byte value) {
            addCriterion("sdkAccess >=", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessLessThan(Byte value) {
            addCriterion("sdkAccess <", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessLessThanOrEqualTo(Byte value) {
            addCriterion("sdkAccess <=", value, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessIn(List<Byte> values) {
            addCriterion("sdkAccess in", values, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessNotIn(List<Byte> values) {
            addCriterion("sdkAccess not in", values, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessBetween(Byte value1, Byte value2) {
            addCriterion("sdkAccess between", value1, value2, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andSdkAccessNotBetween(Byte value1, Byte value2) {
            addCriterion("sdkAccess not between", value1, value2, "sdkAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessIsNull() {
            addCriterion("apiAccess is null");
            return (Criteria) this;
        }

        public Criteria andApiAccessIsNotNull() {
            addCriterion("apiAccess is not null");
            return (Criteria) this;
        }

        public Criteria andApiAccessEqualTo(Byte value) {
            addCriterion("apiAccess =", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessNotEqualTo(Byte value) {
            addCriterion("apiAccess <>", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessGreaterThan(Byte value) {
            addCriterion("apiAccess >", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessGreaterThanOrEqualTo(Byte value) {
            addCriterion("apiAccess >=", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessLessThan(Byte value) {
            addCriterion("apiAccess <", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessLessThanOrEqualTo(Byte value) {
            addCriterion("apiAccess <=", value, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessIn(List<Byte> values) {
            addCriterion("apiAccess in", values, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessNotIn(List<Byte> values) {
            addCriterion("apiAccess not in", values, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessBetween(Byte value1, Byte value2) {
            addCriterion("apiAccess between", value1, value2, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andApiAccessNotBetween(Byte value1, Byte value2) {
            addCriterion("apiAccess not between", value1, value2, "apiAccess");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateIsNull() {
            addCriterion("questionaireRate is null");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateIsNotNull() {
            addCriterion("questionaireRate is not null");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateEqualTo(Integer value) {
            addCriterion("questionaireRate =", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateNotEqualTo(Integer value) {
            addCriterion("questionaireRate <>", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateGreaterThan(Integer value) {
            addCriterion("questionaireRate >", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("questionaireRate >=", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateLessThan(Integer value) {
            addCriterion("questionaireRate <", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateLessThanOrEqualTo(Integer value) {
            addCriterion("questionaireRate <=", value, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateIn(List<Integer> values) {
            addCriterion("questionaireRate in", values, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateNotIn(List<Integer> values) {
            addCriterion("questionaireRate not in", values, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateBetween(Integer value1, Integer value2) {
            addCriterion("questionaireRate between", value1, value2, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andQuestionaireRateNotBetween(Integer value1, Integer value2) {
            addCriterion("questionaireRate not between", value1, value2, "questionaireRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateIsNull() {
            addCriterion("feedbackRate is null");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateIsNotNull() {
            addCriterion("feedbackRate is not null");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateEqualTo(Integer value) {
            addCriterion("feedbackRate =", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateNotEqualTo(Integer value) {
            addCriterion("feedbackRate <>", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateGreaterThan(Integer value) {
            addCriterion("feedbackRate >", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateGreaterThanOrEqualTo(Integer value) {
            addCriterion("feedbackRate >=", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateLessThan(Integer value) {
            addCriterion("feedbackRate <", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateLessThanOrEqualTo(Integer value) {
            addCriterion("feedbackRate <=", value, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateIn(List<Integer> values) {
            addCriterion("feedbackRate in", values, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateNotIn(List<Integer> values) {
            addCriterion("feedbackRate not in", values, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateBetween(Integer value1, Integer value2) {
            addCriterion("feedbackRate between", value1, value2, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andFeedbackRateNotBetween(Integer value1, Integer value2) {
            addCriterion("feedbackRate not between", value1, value2, "feedbackRate");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("LastUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("LastUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("LastUpdateTime =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("LastUpdateTime <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("LastUpdateTime >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("LastUpdateTime <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("LastUpdateTime <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("LastUpdateTime in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("LastUpdateTime not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("LastUpdateTime not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_biz_license
     *
     * @mbg.generated do_not_delete_during_merge Thu Aug 30 11:05:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table app_biz_license
     *
     * @mbg.generated Thu Aug 30 11:05:40 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}