package com.treefinance.saas.grapserver.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskSupport implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Id
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Category
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Type
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Name
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Image
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.Enable
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private Boolean enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.CreateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_support.LastUpdateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Id
     *
     * @return the value of task_support.Id
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Id
     *
     * @param id the value for task_support.Id
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Category
     *
     * @return the value of task_support.Category
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Category
     *
     * @param category the value for task_support.Category
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Type
     *
     * @return the value of task_support.Type
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Type
     *
     * @param type the value for task_support.Type
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Name
     *
     * @return the value of task_support.Name
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Name
     *
     * @param name the value for task_support.Name
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Image
     *
     * @return the value of task_support.Image
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Image
     *
     * @param image the value for task_support.Image
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.Enable
     *
     * @return the value of task_support.Enable
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public Boolean getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.Enable
     *
     * @param enable the value for task_support.Enable
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setEnable(Boolean enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.CreateTime
     *
     * @return the value of task_support.CreateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.CreateTime
     *
     * @param createTime the value for task_support.CreateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_support.LastUpdateTime
     *
     * @return the value of task_support.LastUpdateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_support.LastUpdateTime
     *
     * @param lastUpdateTime the value for task_support.LastUpdateTime
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_support
     *
     * @mbggenerated Tue May 02 11:50:52 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", category=").append(category);
        sb.append(", type=").append(type);
        sb.append(", name=").append(name);
        sb.append(", image=").append(image);
        sb.append(", enable=").append(enable);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}