package com.treefinance.saas.grapserver.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskNextDirective implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.Id
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.TaskId
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private Long taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.Directive
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private String directive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.CreateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_next_directive.LastUpdateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_next_directive
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.Id
     *
     * @return the value of task_next_directive.Id
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.Id
     *
     * @param id the value for task_next_directive.Id
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.TaskId
     *
     * @return the value of task_next_directive.TaskId
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.TaskId
     *
     * @param taskId the value for task_next_directive.TaskId
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.Directive
     *
     * @return the value of task_next_directive.Directive
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public String getDirective() {
        return directive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.Directive
     *
     * @param directive the value for task_next_directive.Directive
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public void setDirective(String directive) {
        this.directive = directive == null ? null : directive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.CreateTime
     *
     * @return the value of task_next_directive.CreateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.CreateTime
     *
     * @param createTime the value for task_next_directive.CreateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_next_directive.LastUpdateTime
     *
     * @return the value of task_next_directive.LastUpdateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_next_directive.LastUpdateTime
     *
     * @param lastUpdateTime the value for task_next_directive.LastUpdateTime
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_next_directive
     *
     * @mbggenerated Wed Apr 26 19:21:20 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", taskId=").append(taskId);
        sb.append(", directive=").append(directive);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append("]");
        return sb.toString();
    }
}